export const characters = [
    {
     "Class_Names": "Quantum Mechanics Class",
     "Anti-colors": "Anti-Quantum Mechanics Class: Deep red, representing the disruptive and chaotic nature of counteracting quantum mechanics.",
     "Anti-Faction": "Anti-Quantum Mechanics Faction: A group of players who specialize in countering quantum mechanics and prioritize the use of advanced countermeasures against quantum-based abilities.",
     "Attack_movement": "bleeding, shrukens, Iron will, fearless, dual parry, slash bombard&nbsp;",
     "Character_Image": require("../images/characters/MaysGemConcept.png"),
     "Character_Name": "May's Gem",
     "Class_missions_1": "Quantum Decryption: A Quantum Mechanics player must use quantum decryption to uncover a hidden message.",
     "Class_missions_2": "Quantum Puzzle: A Quantum Mechanics player must solve a complex quantum puzzle to gain access to a secret facility.",
     "Codename": "Swift",
     "Colors": "Quantum Mechanics Class: Silver-blue, representing the cool, calculated nature of quantum mechanics.",
     "Enemies_Lvls_1": "Level 1: Quantum Interference - Allows the player to disrupt quantum teleportation.",
     "Enemies_Lvls_2": "Level 2: Quantum Detection - Allows the player to detect and locate quantum-based traps or hiding spots.",
     "Enemies_Lvls_3": "Level 3: Quantum Neutralization - Allows the player to neutralize quantum-based abilities of enemies.",
     "Enemies_Lvls_4": "Level 4: Quantum Shielding - Allows the player to create a shield that protects against quantum-based attacks.",
     "Enemies_Lvls_5": "Level 5: Quantum Disruption - Allows the player to create a powerful disruption field that neutralizes quantum-based abilities of all enemies in the area.",
     "Faction": "Quantum Mechanics Faction: A group of players who specialize in quantum mechanics and prioritize the use of advanced quantum-based abilities and technology.",
     "Fighting_background": "From experiments that damaged countless planets came mult-functioning spear heads made from metal clouds . Liquid gems were developed into guns the size of blackholes that shoot planets.",
     "Group_Missions_1": "Quantum Apocalypse: A team of Quantum Mechanics and Sound Engineering players must stop a rogue quantum physicist from destroying the world.",
     "Group_Missions_2": "Quantum Vortex: A team of Quantum Mechanics and Sound Engineering players must create a quantum vortex that will suck the final boss into another dimension.",
     "Group_Missions_3": "Quantum Collision: A team of Quantum Mechanics and Sound Engineering players must use quantum technology to create a powerful energy beam that will collide with the final boss and destroy them.",
     "Group_Missions_4": "Quantum Crisis: A team of Quantum Mechanics and Sound Engineering players must stop a quantum black hole from destroying the world.",
     "Group_Missions_5": "Quantum Entanglement: A Quantum Mechanics player must use quantum entanglement to infiltrate an enemy's mind and gain valuable information.",
     "Group_Missions_6": "Quantum Entanglement: A team of Quantum Mechanics and Circuit Design players must use quantum entanglement to control the final boss's mind and defeat them.",
     "Group_Missions_7": "Quantum Escape: A team of Quantum Mechanics and Circuit Design players must escape from a high-security prison using quantum technology.",
     "Group_Missions_8": "Quantum Heist: A team of Quantum Mechanics and Circuit Design players must infiltrate a high-security facility to steal a powerful quantum computer.",
     "Group_Missions_9": "Quantum Paradox: A team of Quantum Mechanics and Circuit Design players must navigate a quantum maze to reach the final boss and stop them from creating a paradox that will destroy the universe.",
     "Group_Missions_10": "Quantum Rift: A Quantum Mechanics player must navigate a dangerous quantum rift to retrieve a powerful energy source for the team.",
     "Locations": "May’s Gem-Exoplanet outposts spread across the cosmos",
     "Long_Desc": "Quantum Mechanics Class: \"Unlock the power of quantum physics and harness the energy of subatomic particles to unleash devastating attacks on your enemies. With the Quantum Mechanics class, players can manipulate time and space to gain the upper hand in battle and outsmart their opponents. Upgrade your skills to unlock even more powerful abilities and dominate the battlefield.\"",
     "Nickname": "MG",
     "Pick_a_power": "Quantum Mechanics Class will focus on the study of Quantum mechanics, which is the branch of physics that deals with the behavior of subatomic particles.",
     "Pitch": "To fast to be tracked with attacking. Can do some crazy shit.",
     "Power_Level_1": "Level 1: Quantum Teleportation - Allows the player to teleport short distances.",
     "Power_Level_2": "Level 2: Quantum Entanglement - Allows the player to share information and coordinate actions with other players.",
     "Power_Level_3": "Level 3: Quantum Hologram - Allows the player to create a holographic decoy to distract enemies.",
     "Power_Level_4": "Level 4: Quantum Time Dilation - Allows the player to slow down time for a brief period.",
     "Power_Level_5": "Level 5: Quantum Superposition - Allows the player to be in two places at once, creating a double of themselves.",
     "Reference_1": "Baraka",
     "Reference_2": "Kung Lou",
     "Reference_3": "Jax",
     "Reference_4": "Jade",
     "Reference_5": "Scarlet",
     "Reference_6": "Ferra/Torra",
     "Reference_7": "Swamp Thing",
     "Science": "Quantum",
     "Short_desc": "Quantum Mechanics class, players will have access to powerful quantum-based attacks",
     "Some_attacks": "Microwave throwable - stuns/cook/Disintegrate/evaporated - MG",
     "Type": "Ghost",
     "Unique_Missions_1": "Quantum Decryption: A Quantum Mechanics player must use quantum decryption to uncover a hidden message.",
     "Unique_Missions_2": "Quantum Puzzle: A Quantum Mechanics player must solve a complex quantum puzzle to gain access to a secret facility.",
     "Weaknesses": "Anti-Quantum Mechanics Class: This class would be focused on disrupting and negating the effects of quantum-based attacks, such as creating quantum interference to disrupt quantum teleportation, or being able to detect and neutralize quantum-based traps or hiding spots.",
     "Weapon_B": "Spear Hooks - Chibot - Superweapon classed.",
     "Weapon_Name": "Spear Hooks - Chibots = Superweapon class - May’s Gem - The engineer",
     "Weapon_playstyle": "Spear Hooks - grapple anything, pull towards or away, multi-tip heads.",
     "Weapon_Type": "Spear Hooks",
     "Weapons": "Liquid Sword",
     "Balance": 3.368026410570902,
     "Chin": 1.747322546593903,
     "Agility": 2.1710352732173828,
     "Engineering": 2.770842819508573,
     "Precision": -4.503605252665233,
     "Dexterity": -5,
     "Intuition": -3.590380317799357,
     "Base stats": -1.704920683168477,
     "ATK": 5.045382978262191,
     "SPD": -0.41674709624236783,
     "SCI-fi": 10,
     "DEF": 1.937912267026526,
     "ENERGY": 9.338174937452404,
     "ENhanded": 3.939071074212828,
     "TECH": 5.035612879123576
    },
    {
     "Class_Names": "Sound Engineering Class",
     "Anti-colors": "Anti-Sound Engineering Class: Dark gray, representing the sound-cancellation and neutralizing aspect of counteracting sound-based attacks.",
     "Anti-Faction": "Anti-Sound Engineering Faction: A group of players who specialize in countering sound engineering and prioritize the use of advanced countermeasures against sound-based abilities.",
     "Attack_movement": "Kicks, punches, Heavy slams, life holds, throws, and grappler&nbsp;",
     "Character_Image": require("../images/characters/BrilliantNeptuneConcept.png"),
     "Character_Name": "Brilliant Neptune",
     "Class_missions_1": "Sonic Scramble: A Sound Engineering player must use advanced sound equipment to scramble enemy communications.",
     "Class_missions_2": "Sound Surveillance: A Sound Engineering player must use advanced listening equipment to gather intel on an enemy's plans.",
     "Codename": "FIGHTer",
     "Colors": "Sound Engineering Class: Deep purple, representing the mysterious and powerful nature of sound.",
     "Enemies_Lvls_1": "Level 1: Sound Cancellation - Allows the player to create a sound-cancellation field that neutralizes sound-based attacks.",
     "Enemies_Lvls_2": "Level 2: Counter-Frequency - Allows the player to use counter-frequency weapons to neutralize sound-based attacks.",
     "Enemies_Lvls_3": "Level 3: Sound Immunity - Allows the player to become immune to certain types of sound-based attacks.",
     "Enemies_Lvls_4": "Level 4: Sound Analysis - Allows the player to analyze and identify sound-based abilities of enemies.",
     "Enemies_Lvls_5": "Level 5: Sound Neutralization - Allows the player to neutralize the sound-based abilities of all enemies in the area.",
     "Faction": "Sound Engineering Faction: A group of players who specialize in sound engineering and prioritize the use of advanced sound-based abilities and technology.",
     "Fighting_background": "Brutes who avoid high stress situations by making emotional decisions with logical backing. Years of walking many opposing paths led to comprising critical points in structures. The right blow breaks bricks.",
     "Group_Missions_1": "Sonic Barrier: A Sound Engineering player must create a sonic barrier to protect a city under attack.",
     "Group_Missions_2": "Sound",
     "Group_Missions_3": "Sonic Boom: A team of Sound Engineering and Armaments Design players must create a powerful sonic weapon to defeat the final boss and save the world.",
     "Group_Missions_4": "Sonic Sweep: A Sound Engineering player must infiltrate and clear an enemy base of sound-controlled robots.",
     "Group_Missions_5": "Sonic Tempest: A team of Sound Engineering and Armaments Design players must create a sonic storm that will destroy the final boss and their army.",
     "Group_Missions_6": "Sound Barrier: A team of Sound Engineering and Armaments Design players must protect a city from a sonic attack.",
     "Group_Missions_7": "Sound Siege: A team of Sound Engineering and Armaments Design players must defend a city against an invasion of sound-controlled robots.",
     "Group_Missions_8": "Sound",
     "Group_Missions_9": "Sound",
     "Group_Missions_10": "Sound",
     "Locations": "Brilliant Nigga-Hidden society with floating boulders in a motion powered by tech only known to membs",
     "Long_Desc": "Sound Engineering Class: \"Control the power of sound to your advantage and turn it into a weapon against your enemies. The Sound Engineering class allows players to create sonic blasts, manipulate sound waves, and even hack into electronic systems using sound. Upgrade your skills to unlock even more powerful sound-based abilities and decimate your foes.\"",
     "Nickname": "BN",
     "Pick_a_power": "Sound Engineering Class will focus on the study of sound and its effects, including the design and use of sound systems.",
     "Pitch": "Can brawl with the elephant bosses",
     "Power_Level_1": "Level 1: Sonic Blast - Allows the player to create a blast of sound that damages enemies.",
     "Power_Level_2": "Level 2: Sound Barrier - Allows the player to create a barrier that protects the player and allies from damage.",
     "Power_Level_3": "Level 3: Sonic Scrambler - Allows the player to scramble enemy communications.",
     "Power_Level_4": "Level 4: Sound Wave - Allows the player to create a wave of sound that knocks enemies off their feet.",
     "Power_Level_5": "Level 5: Sonic Boom - Allows the player to create a devastating blast of sound that damages all enemies in the area.",
     "Reference_1": "Johnny Cage",
     "Reference_2": "Errmac",
     "Reference_3": "Lou Kang",
     "Reference_4": "Sub Zero",
     "Reference_5": "Rain",
     "Reference_6": "Goro",
     "Reference_7": "NightWolf",
     "Science": "Sound",
     "Short_desc": "Sound Engineering class will allow players to manipulate sound to their advantage.",
     "Some_attacks": "Walking Combat - Confusion Blow/Cross Reference/Encompassed Combo/Art of Insight - BN",
     "Type": "Electric",
     "Unique_Missions_1": "Sonic Scramble: A Sound Engineering player must use advanced sound equipment to scramble enemy communications.",
     "Unique_Missions_2": "Sound Surveillance: A Sound Engineering player must use advanced listening equipment to gather intel on an enemy's plans.",
     "Weaknesses": "Anti-Sound Engineering Class: This class would be focused on creating sound-cancellation fields or using counter-frequency weapons to neutralize sound-based attacks.",
     "Weapon_B": "Melee - Strength and Powerhouse",
     "Weapon_Name": "Melee- Powerhouse - BN&nbsp;",
     "Weapon_playstyle": "Melee - combos, situational awareness, and debuff/submission holds",
     "Weapon_Type": "Strength - Melee",
     "Weapons": "Super MMA",
     "Balance": -1.5645723301265217,
     "Chin": -0.3888773706602757,
     "Agility": 3.9678116756030306,
     "Engineering": 1.7748793544086778,
     "Precision": 9.535280284140235,
     "Dexterity": -4.060234091190124,
     "Intuition": 8.842221883342209,
     "Base stats": 3.098435804350224,
     "ATK": 9.338094629697085,
     "SPD": 1.5262366414687598,
     "SCI-fi": -5,
     "DEF": 10,
     "ENERGY": -1.3032771650660742,
     "ENhanded": -4.304386421003466,
     "TECH": -3.6243795315155687
    },
    {
     "Class_Names": "Armaments Design Class",
     "Anti-colors": "Anti-Armaments Design Class: Olive green, representing the counteractive and defensive aspect of counteracting enemy weapons.",
     "Anti-Faction": "Anti-Armaments Faction: A group of players who specialize in countering armaments and prioritize the use of advanced countermeasures against enemy weapons.",
     "Attack_movement": "pistol, shotgun, AK-74, Assualt Rifle, rockets, nads. chaingun&nbsp;",
     "Character_Image": require("../images/characters/DrBirdsconcept.png"),
     "Character_Name": "Dr Birds",
     "Class_missions_1": "Armaments Upgrade: An Armaments Design player must upgrade and maintain the team's weapons and equipment.",
     "Class_missions_2": "Armament Class Mission",
     "Codename": "General",
     "Colors": "Armaments Design Class: Metallic gray, representing the technological and militaristic aspect of weapons design.",
     "Enemies_Lvls_1": "Level 1: Weapon Analysis - Allows the player to analyze and identify enemy weapons.",
     "Enemies_Lvls_2": "Level 2: Armor Analysis - Allows the player to analyze and identify enemy armor.",
     "Enemies_Lvls_3": "Level 3: Explosive Analysis - Allows the player to analyze and identify explosive devices.",
     "Enemies_Lvls_4": "Level 4: Robotics Analysis - Allows the player to analyze and identify robotic units.",
     "Enemies_Lvls_5": "Level 5: Tactical Analysis - Allows the player to analyze and counter enemy tactical maneuvers.",
     "Faction": "Armaments Faction: A group of players who specialize in armaments design and prioritize the use of advanced weapons and equipment.",
     "Fighting_background": "TS/Poly people gather to accomplish unbelievable REDACATED with nothing but paper, pens, and brainpower for money. The resources, materials, and equipment were all belong to the owners. Drive weaponized is one of the most precious commodities in the universe.&nbsp;",
     "Group_Missions_1": "Armaments Retrieval: An Armaments Design player must infiltrate an enemy facility and retrieve stolen weapons and technology.",
     "Group_Missions_2": "Armaments",
     "Group_Missions_3": "Armaments",
     "Group_Missions_4": "Armaments",
     "Group_Missions_5": "Armaments",
     "Group_Missions_6": "Armaments",
     "Group_Missions_7": "Armaments",
     "Group_Missions_8": "Armaments",
     "Group_Missions_9": "Armaments",
     "Group_Missions_10": "Armaments",
     "Locations": "Dr. Birds.-Rundown hi-tech van. Signs of crazed amn living in van on a investigation.",
     "Long_Desc": "Armaments Design Class: \"Become a master of warfare and equip yourself with the latest and greatest weapons and military equipment. The Armaments Design class gives players access to a wide range of deadly weapons, from high-tech guns to powerful melee weapons. Upgrade your skills to unlock new weapons and upgrades and become the ultimate soldier.\"",
     "Nickname": "DB",
     "Pick_a_power": "Armaments Design Class will focus on the design and development of weapons and other military equipment.",
     "Pitch": "EXO suit with anger issues. Him and the suit",
     "Power_Level_1": "Level 1: Weapon Proficiency - Allows the player to use a variety of weapons with increased accuracy and efficiency.",
     "Power_Level_2": "Level 2: Armor Proficiency - Allows the player to wear armor that provides increased protection.",
     "Power_Level_3": "Level 3: Explosive Proficiency - Allows the player to use and create a variety of explosive devices.",
     "Power_Level_4": "Level 4: Robotics Proficiency - Allows the player to use and control robotic units.",
     "Power_Level_5": "Level 5: Tactical Proficiency - Allows the player to plan and execute complex tactical maneuvers.",
     "Reference_1": "Scropion",
     "Reference_2": "Eron Black",
     "Reference_3": "Shan Khan",
     "Reference_4": "Raiden",
     "Reference_5": "Kortal Khan",
     "Reference_6": "Kano",
     "Reference_7": "Kenshi",
     "Science": "Armaments",
     "Short_desc": "Armaments Design class will give players access to advanced weapons and military equipment,",
     "Some_attacks": "Special Ops -Smart Green Bullets/Blue Velocity Bullets/Hulk Suit/Satellite charge/Knife Bullets -DB",
     "Type": "Dark",
     "Unique_Missions_1": "Armaments Upgrade: An Armaments Design player must upgrade and maintain the team's weapons and equipment.",
     "Unique_Missions_2": "Armament Unique Mission",
     "Weaknesses": "Anti-Armaments Design Class: This class would be focused on creating weapons and equipment specifically designed to counter and neutralize the effects of enemy weapons, such as creating anti-tank weapons to counter armored vehicles.",
     "Weapon_B": "Gunner -gadgets and distance control",
     "Weapon_Name": "Gunner - gadgets &amp; distance control - DB",
     "Weapon_playstyle": "Gunner - different ammo types, rate of fire, and bullet spray.",
     "Weapon_Type": "Gadgets - Gunner",
     "Weapons": "John Wick",
     "Balance": -5,
     "Chin": 10,
     "Agility": -1.4873880895301976,
     "Engineering": -2.3454120590370326,
     "Precision": 3.8206741275472336,
     "Dexterity": 7.86988247060032,
     "Intuition": 0.5476543851080331,
     "Base stats": 4.143329789444326,
     "ATK": 9.304604023938301,
     "SPD": 3.407723700070031,
     "SCI-fi": -2.492552756527023,
     "DEF": -4.241997475137235,
     "ENERGY": 8.61426015469545,
     "ENhanded": -0.6963777757819614,
     "TECH": 7.354310623813264
    },
    {
     "Class_Names": "Circuit Design Class",
     "Anti-colors": "Anti-Circuit Design Class: Dark purple, representing the secretive and protective aspect of counteracting hacking.",
     "Anti-Faction": "Anti-Circuit Design Faction: A group of players who specialize in countering circuit design and prioritize the use of advanced countermeasures against hacking and cyber attacks.",
     "Attack_movement": "&nbsp;Robotic limbs, groot expand, morph, devastation beam blasts, duplication, and self destruction",
     "Character_Image": require("../images/characters/BlindBlackConcept.png"),
     "Character_Name": "Blind Black",
     "Class_missions_1": "Circuit Surveillance: A Circuit Design player must use surveillance drones to gather intel on an enemy's movements.",
     "Class_missions_2": "Circuit Hack: A Circuit Design player must hack into an enemy's computer systems to steal valuable information.",
     "Codename": "Coder",
     "Colors": "Circuit Design Class: Electric blue, representing the high-tech and digital aspect of circuit design.",
     "Enemies_Lvls_1": "Level 1: Firewall - Allows the player to create a firewall that protects against hacking.",
     "Enemies_Lvls_2": "Level 2: Intrusion Detection - Allows the player to detect and locate hacking attempts.",
     "Enemies_Lvls_3": "Level 3: Encryption - Allows the player to encrypt their systems and protect against hacking.",
     "Enemies_Lvls_4": "Level 4: Counter-Hacking - Allows the player to hack into and disrupt enemy hacking attempts.",
     "Enemies_Lvls_5": "Level 5: Cyber Immunity - Allows the player to become immune to certain types of hacking and cyber attacks.",
     "Faction": "Circuit Design Faction: A group of players who specialize in circuit design and prioritize the use of advanced technology and hacking abilities.",
     "Fighting_background": "Technicians can turn a pen into a sword. Always adding complexity to plans for a satisfying win. AI isn’t ruthless, human hating, nor defective. Calculated risks based on pushing limits without a fear of failure can led to avoidable mishaps.&nbsp;",
     "Group_Missions_1": "Circuit Overload: A Circuit Design player must hack into and overload the enemy's power grid to disable their systems.",
     "Group_Missions_2": "Cyber",
     "Group_Missions_3": "Circuit Sabotage: A Circuit Design player must hack into and sabotage the enemy's robots and drones.",
     "Group_Missions_4": "Cyber Assault: A team of Circuit Design and Armaments Design players must hack into and control the final boss's robotic body and shut it down.",
     "Group_Missions_5": "Cyber Attack: A team of Circuit Design and Armaments Design players must hack into and take control of an enemy's military drones.",
     "Group_Missions_6": "Cyber Overload: A team of Circuit Design and Armaments Design players must overload the final boss's systems with a powerful EMP blast, shutting them down.",
     "Group_Missions_7": "Cyber",
     "Group_Missions_8": "Cyber",
     "Group_Missions_9": "Cyber",
     "Group_Missions_10": "Cyber",
     "Locations": "Blind Black-Small suburban house with normal garage acting as the cover for the huge workshop.",
     "Long_Desc": "Circuit Design Class: \"Hack into and control electronic systems to gain an advantage in battle. The Circuit Design class allows players to hack into enemy robots, turrets and other electronic systems to control them, or disrupt them to give you the upper hand. Upgrade your skills to unlock even more powerful hacking abilities and become a master of technology.\"",
     "Nickname": "BB",
     "Pick_a_power": "Circuit Design Class will focus on the design and development of electronic circuits and systems.",
     "Pitch": "Can hack into KE alien level encryption",
     "Power_Level_1": "Level 1: Hacking - Allows the player to hack into enemy systems and control them.",
     "Power_Level_2": "Level 2: Surveillance - Allows the player to use surveillance drones to gather information.",
     "Power_Level_3": "Level 3:Data Analysis - Allows the player to analyze and interpret data quickly and efficiently.",
     "Power_Level_4": "Level 4: Encryption - Allows the player to encrypt and protect their own systems from hacking.",
     "Power_Level_5": "Level 5: Remote Control - Allows the player to remotely control and hack into multiple systems at once.",
     "Reference_1": "Kitana",
     "Reference_2": "Kollector",
     "Reference_3": "Predator",
     "Reference_4": "Sonya",
     "Reference_5": "Jackie",
     "Reference_6": "Triborg",
     "Reference_7": "Frost",
     "Science": "Circuits",
     "Short_desc": "Circuit Design class will allow players to hack and control electronic systems.",
     "Some_attacks": "“Wheelie” - dash/charge/float/sentry - BB",
     "Type": "Normal",
     "Unique_Missions_1": "Circuit Hack: A Circuit Design player must hack into an enemy's computer systems to steal valuable information.",
     "Unique_Missions_2": "Circuit Surveillance: A Circuit Design player must use surveillance drones to gather intel on an enemy's movements.",
     "Weaknesses": "Anti-Circuit Design Class: This class would be focused on creating countermeasures to hack attacks, such as creating firewalls, intrusion detection systems and other security systems.",
     "Weapon_B": "Insight - Staff &amp; Daggers",
     "Weapon_Name": "Insight - Staff, Daggers, hack &amp; dash - BB",
     "Weapon_playstyle": "Staff -&nbsp; Chain enemies in a.o.a chain attacks, spacial awareness, acrobatic",
     "Weapon_Type": "Insight - Staff",
     "Weapons": "AI Drone Staff",
     "Balance": -4.421479776437361,
     "Chin": 1.5445193487396622,
     "Agility": -2.820939725291096,
     "Engineering": -2.371195870210199,
     "Precision": 3.7071096087973245,
     "Dexterity": -4.035906514664736,
     "Intuition": 7.361917444792466,
     "Base stats": 6.976778723897116,
     "ATK": 1.3628149695694214,
     "SPD": -5,
     "SCI-fi": -4.3763813755177,
     "DEF": -3.6524859065076622,
     "ENERGY": -2.075812798547328,
     "ENhanded": 0.6379830087188836,
     "TECH": 10
    },
    {
     "Class_Names": "DNA Research Class",
     "Anti-colors": "Anti-DNA Research Class: Dark blue, representing the neutralizing and protective aspect of counteracting genetic-based attacks.",
     "Anti-Faction": "Anti-DNA Research Faction: A group of players who specialize in countering DNA research and prioritize the use of advanced countermeasures against genetic-based abilities.",
     "Attack_movement": "energy blasts/beams, speed drain, slow-mo wave, passing by debris and glasses sharps, super speed chain attack, concusive overhead strikes&nbsp;",
     "Character_Image": require("../images/characters/RayConcept.png"),
     "Character_Name": "Ray",
     "Class_missions_1": "Genetic Cloning: A DNA Research player must clone a rare plant that holds the key to a secret location.",
     "Class_missions_2": "Genetic Analysis: A DNA Research player must analyze genetic samples to uncover a hidden enemy's weakness.",
     "Codename": "Splicer",
     "Colors": "DNA Research Class: Bright green, representing the life-giving and regenerative aspect of genetics.",
     "Enemies_Lvls_1": "Level 1: Genetic Analysis - Allows the player to analyze and identify genetic-based abilities of enemies.",
     "Enemies_Lvls_2": "Level 2: Genetic Neutralization - Allows the player to neutralize genetic-based abilities of enemies.",
     "Enemies_Lvls_3": "Level 3: Genetic Immunity - Allows the player to become immune to certain types of genetic-based attacks.",
     "Enemies_Lvls_4": "Level 4: Genetic Decontamination - Allows the player to decontaminate areas affected by genetic-based attacks.",
     "Enemies_Lvls_5": "Level 5: Genetic Disruption - Allows the player to create a powerful disruption field that neutralizes genetic-based abilities of all enemies in the area.",
     "Faction": "DNA Research Faction: A group of players who specialize in DNA research and prioritize the use of genetic-based abilities and technology.",
     "Fighting_background": "Unknown gene splicing practice, that’s half ancient and half futuristic, of manipulating the laws of living cells that other members find disturbing.",
     "Group_Missions_1": "Gene Research: A team of DNA Research and Chemical Engineering players must recover stolen DNA samples from a rival corporation.",
     "Group_Missions_2": "Genetic",
     "Group_Missions_3": "Genetic Evolution: A team of DNA Research and Chemical Engineering players must use genetic engineering to create a powerful organism to defeat the final boss.",
     "Group_Missions_4": "Genetic Experiment: A DNA Research player must sabotage an unethical genetic experiment being conducted by the enemy.",
     "Group_Missions_5": "Genetic Experiment: A team of DNA Research and Chemical Engineering players must infiltrate a secret lab and stop an unethical genetic experiment.",
     "Group_Missions_6": "Genetic Immunity: A DNA Research player must create a virus to shut down the enemy's genetic weapon.",
     "Group_Missions_7": "Genetic Immunity: A team of DNA Research and Chemical Engineering players must use genetic engineering to create a virus that will shut down the final boss's systems.",
     "Group_Missions_8": "Genetic Warfare: A team of DNA Research and Chemical Engineering players must stop a rival corporation from releasing a genetically-engineered weapon.",
     "Group_Missions_9": "Genetic",
     "Group_Missions_10": "Genetic",
     "Locations": "RAY-Gray compartementlized lab with experiments in various completed stages.",
     "Long_Desc": "DNA Research Class: \"Manipulate genetics to gain superhuman abilities and become a force to be reckoned with. The DNA Research class gives players the ability to enhance their strength, speed, and agility, as well as granting them the power to regenerate health and resist damage. Upgrade your skills to unlock even more powerful genetic abilities and become a true superhero.\"",
     "Nickname": "R",
     "Pick_a_power": "DNA Research Class will focus on the study of DNA and its role in genetics and biotechnology.",
     "Pitch": "Can land a long shot throw into an small eye",
     "Power_Level_1": "Level 1: Genetic Healing - Allows the player to heal themselves and allies using genetic manipulation.",
     "Power_Level_2": "Level 2: Genetic Enhancement - Allows the player to enhance their own physical abilities.",
     "Power_Level_3": "Level 3: Genetic Immunity - Allows the player to become immune to certain types of attacks.",
     "Power_Level_4": "Level 4: Genetic Manipulation - Allows the player to manipulate the genetics of plants and animals.",
     "Power_Level_5": "Level 5: Genetic Weaponization - Allows the player to create and use genetic weapons.",
     "Reference_1": "Devorah",
     "Reference_2": "Shang Tsang",
     "Reference_3": "Qui Chi",
     "Reference_4": "Noob Saibot",
     "Reference_5": "Smoke",
     "Reference_6": "Reptile",
     "Reference_7": "Kabel",
     "Science": "DNA",
     "Short_desc": "DNA Research class will give players the ability to manipulate genetics,",
     "Some_attacks": "Cadagger - MIA/Cell Foam/Splicer/Injections - R",
     "Type": "Fairy",
     "Unique_Missions_1": "Genetic Analysis: A DNA Research player must analyze genetic samples to uncover a hidden enemy's weakness.",
     "Unique_Missions_2": "Genetic Cloning: A DNA Research player must clone a rare plant that holds the key to a secret location.",
     "Weaknesses": "Anti-DNA Research Class: This class would be focused on creating countermeasures to genetic-based attacks, such as creating genetic antidotes to neutralize genetic poisons, or creating genetic vaccines to protect against genetic diseases.",
     "Weapon_B": "Energy Waves - Movement finder&nbsp;",
     "Weapon_Name": "Energy waves - Movement finder - Zoo/Bio - RAY Genetictis",
     "Weapon_playstyle": "Movement Energy Waves - earth shaking, dazing from running, overhead strikes like lighting",
     "Weapon_Type": "Energy Waves - Movement",
     "Weapons": "DNA Syringes ",
     "Balance": 7.664703013117116,
     "Chin": -1.6198568134967433,
     "Agility": 10,
     "Engineering": 7.148938539433933,
     "Precision": 8.937983036394826,
     "Dexterity": 6.109235086888905,
     "Intuition": 5.343416524628022,
     "Base stats": 5.166690542249727,
     "ATK": 6.939680868443503,
     "SPD": 9.697427035020752,
     "SCI-fi": -1.5522398696919693,
     "DEF": -5,
     "ENERGY": -3.6920039393358683,
     "ENhanded": -0.7366504342129998,
     "TECH": 8.166774193017005
    },
    {
     "Class_Names": "Chemical Engineering Class",
     "Anti-colors": "Anti-Chemical Engineering Class: Bright yellow, representing the neutralizing and protective aspect of counteracting chemical-based attacks.",
     "Anti-Faction": "Anti-Chemical Engineering Faction: A group of players who specialize in countering chemical engineering and prioritize the use of advanced countermeasures against chemical-based abilities.",
     "Attack_movement": "Marked, Rapid fire, cluster shells, ally buffs, defense shredder, air support, cannon slashed.",
     "Character_Image": require("../images/characters/BallConcept.png"),
     "Character_Name": "Ball",
     "Class_missions_1": "Chemical Fusion: A Chemical Engineering player must create a new chemical compound to fuel a secret weapon.",
     "Class_missions_2": "Chemical Class Mission",
     "Codename": "Baller",
     "Colors": "Chemical Engineering Class: Bright orange, representing the explosive and reactive nature of chemicals.",
     "Enemies_Lvls_1": "Level 1: Chemical Analysis - Allows the player to analyze and identify chemicals.",
     "Enemies_Lvls_2": "Level 2: Chemical Neutralization - Allows the player to neutralize chemical-based abilities of enemies.",
     "Enemies_Lvls_3": "Level 3: Chemical Immunity - Allows the player to become immune to certain types of chemical-based attacks.",
     "Enemies_Lvls_4": "Level 4: Chemical Decontamination - Allows the player to decontaminate areas affected by chemical-based attacks.",
     "Enemies_Lvls_5": "Level 5: Chemical Disruption - Allows the player to create a powerful disruption field that neutralizes chemical-based abilities of all enemies in the area.",
     "Faction": "Chemical Engineering Faction: A group of players who specialize in chemical engineering and prioritize the use of chemical-based abilities and technology.",
     "Fighting_background": "Unpredictability leads to confusion. Keep the enemy guessing between long-range precision bolts and close-range plant swarms that confuse even in hindsight. Destroy and create new paths for sick people.",
     "Group_Missions_1": "Chemical Warfare: A Chemical Engineering player must create and deploy chemical weapons to sabotage the enemy's operations.",
     "Group_Missions_2": "Chemical",
     "Group_Missions_3": "Chemical",
     "Group_Missions_4": "Chemical",
     "Group_Missions_5": "Chemical",
     "Group_Missions_6": "Chemical",
     "Group_Missions_7": "Chemical",
     "Group_Missions_8": "Chemical",
     "Group_Missions_9": "Chemical",
     "Group_Missions_10": "Chemical",
     "Locations": "Ball-Underground flower lab with plant based equipment, walls, and containers.",
     "Long_Desc": "Chemical Engineering Class: \"Harness the power of chemical reactions to defeat your enemies. The Chemical Engineering class allows players to create powerful chemical weapons and gadgets, such as toxic gas, acid rain, and even napalm. Upgrade your skills to unlock even more powerful chemical abilities and become a master of destruction.\"",
     "Nickname": "B",
     "Pick_a_power": "Chemical Engineering Class will focus on the design and production of chemicals and chemical processes.",
     "Pitch": "Counter Boarbo Energy",
     "Power_Level_1": "Level 1: Chemical Mixing - Allows the player to create and use a variety of chemical compounds.",
     "Power_Level_2": "Level 2: Chemical Analysis - Allows the player to analyze and identify chemicals.",
     "Power_Level_3": "Level 3: Chemical Resistance - Allows the player to become resistant to certain types of chemicals.",
     "Power_Level_4": "Level 4: Chemical Explosion - Allows the player to create explosive chemical reactions.",
     "Power_Level_5": "Level 5: Chemical Engineering - Allows the player to use advanced chemical engineering techniques.",
     "Reference_1": "Shinnok",
     "Reference_2": "Poison Ivy",
     "Reference_3": "Cetrion",
     "Reference_4": "Geras",
     "Reference_5": "Krontas",
     "Reference_6": "Tremor",
     "Reference_7": "Green Lantern",
     "Science": "Chemicals",
     "Short_desc": "Chemical Engineering class will allow players to harness the power of chemical reactions.",
     "Some_attacks": "Vines - snakes/whips/wrap/jungle trunk - B",
     "Type": "Dragon",
     "Unique_Missions_1": "Chemical Fusion: A Chemical Engineering player must create a new chemical compound to fuel a secret weapon.",
     "Unique_Missions_2": "Chemcial Unique Mission",
     "Weaknesses": "Anti-Chemical Engineering Class: This class would be focused on creating countermeasures to chemical-based attacks, such as creating chemical neutralizers to neutralize toxic gases, or creating chemical filters to protect against acid rain.",
     "Weapon_B": "Strange Luck- Launcher&nbsp;",
     "Weapon_Name": "Strange Luck - Launcher &amp; area of focus - Ball Plants",
     "Weapon_playstyle": "Strange Luck - force push, pull, choke, psychokinesis, mild telepathy,",
     "Weapon_Type": "Strange Plant Luck",
     "Weapons": "Plants &amp; Potions",
     "Balance": -4.036445539902348,
     "Chin": 5.383489137694314,
     "Agility": 3.3685005057937207,
     "Engineering": 10,
     "Precision": -5,
     "Dexterity": 7.903637249182074,
     "Intuition": 0.805962651965821,
     "Base stats": -0.3828316673405494,
     "ATK": 5.110580355649539,
     "SPD": -0.2551550361693371,
     "SCI-fi": 7.872647192873956,
     "DEF": 8.635528872103944,
     "ENERGY": 0.42069745876645026,
     "ENhanded": 6.7474016574854545,
     "TECH": 5.764307848042732
    }
   ]
